# Generated by Django 3.2.20 on 2023-07-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0006_alter_patient_bp_1d_alter_patient_bp_1s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bp_1d',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bp_1s',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bp_2d',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bp_2s',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hdl',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
    ]
